language: go
go:
- 1.8
- tip

before_deploy:
  - GOOS=linux GOARCH=amd64 go build -a -o build/journey.linux-amd64 -ldflags "-X main.Version=$(git describe --tags 2>/dev/null | cut -c 2-) -s -w" .
  - GOOS=darwin GOARCH=amd64 go build -a -o build/journey.darwin-amd64 -ldflags "-X main.Version=$(git describe --tags 2>/dev/null | cut -c 2-) -s -w" .
  - GOOS=windows GOARCH=amd64 go build -a -o build/journey.windows-amd64 -ldflags "-X main.Version=$(git describe --tags 2>/dev/null | cut -c 2-) -s -w" .
  - find build -name 'journey*' | xargs -I{} tar czf {}.tar.gz {}
  - shasum -a 256 build/* > build/sha256sum.txt
  - cat build/sha256sum.txt

deploy:
  - provider: releases
    api_key:
      secure: ol7WiiJ+MooWAVQF4RjM1GY7AgOrDu9MD0WPU02yfCr9s+OnhIli6kqaFK+NZqYraVUV+j71p4VieaLNoxXcjkmGDBrjaEnXRU6bxaT/lwERCQtGvZjhv40S/FgqqywUOXAUUcle5VNkmorinDzWFcRUU6NScc24+J9Qr1siWIfd6kqLmRkIh2QBqoT4Z1/pFeaxQRsGm1IYLwD/MdEEd6hErMNqQb0S4Cn/tmAYcOai3LwwoIZLrmjLpB2HrTNAOj+3WW37XJicHTEhqbtgibljOzgrmA+oV/qj6H5asIMbqBZQLCEe6H7mYOSOlXLjKugqKCx/VlhVvkQSA8ryCszmrWIkHyBTFFGTHfVYBR8d1EUrItCe/Ef4k1BeE4mmXFY9q3cbCxTvUDkvYJB5LUJyxIQu0e/GQ7oP1HULtQB6LKq+zCu0jLmhSGjtgs+X7f/DomY9gR871D5V76LFrUquUEYhvdsmv9K3srb5jN4r0kPzdPucx++xGxKS8lLsmLuLf3S16kTNpCvElYEJqB6yrAoIZ5kFbYTj9/UWK+0jS4p8sCRK6g0666tLpmkMskDabUUySjPdAikArnHQ5uOVwr7rCRq1mq+ItmMjH0YPIS/yA9N+449/5a14UTZMLwOnIk1gOtRTQ2GqTP3yiwKN6sIHGeea0qComd7i1mU=
    skip_cleanup: true
    on:
      go: 1.8
      repo: nexdrew/journey
      tags: true
    file:
      - build/journey.linux-amd64.tar.gz
      - build/journey.darwin-amd64.tar.gz
      - build/journey.windows-amd64.tar.gz
      - build/sha256sum.txt
